---
- name: check the path to kubectl
  command: find / -name kubectl # noqa 301
  retries: 5
  delay: 2
  register: kubectl

- name: Ensure that kube config are present
  stat:
    path: /root/.kube/config
  register: kubeconfig

- name: Fail if k8s config was not found
  fail:
    msg: "Kuberbernetes configuration wasn't found in the default folder"
  when: kubeconfig.stat.exists == 'true'

- name: Copy portworx configuration file to the remote master node
  copy:
    src: portworx_essentials.yaml
    dest: /root/portworx_essentials.yaml
    mode: '0644'

- name: Delete portworx configuration on the kubernetes cluster
  command: '{{ kubectl.stdout }} delete -f /root/portworx_essentials.yaml' # noqa 301

- name: Cleanup the files
  file:
    path: /root/portworx_essentials.yaml
    state: absent
