---
- hosts: localhost
  gather_facts: false
  roles:
    - role: ocp4_verifications
      tags:
       - check
       - grafana
       - pwx
       - postcheck
       - perf
       - report
      when: infra_type == "ocp4"
    - role: ocp4_grafana_install
      tags:
       - grafana
      when: infra_type == "ocp4" and grafana_enable|bool
    - role: ocp4_pwx_install
      tags:
       - pwx
      when: infra_type == "ocp4"
    - role: ocp4_post_verifications
      tags:
       - postcheck
      when: infra_type == "ocp4"
    - role: ocp4_performance
      tags:
       - perf
      when: infra_type == "ocp4"
    - role: ocp4_report
      tags:
       - report
      when: infra_type == "ocp4"

- hosts: kube-node
  gather_facts: false
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - role: check_block_devices
      when: infra_type == "kubernetes"

- hosts: kube-master[0]
  gather_facts: false
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - role: cluster_install
      when: infra_type == "kubernetes"