apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: default-grafanadatasource
  namespace: kube-system
spec:
  datasources:
    - basicAuthUser: pwx-user
      access: proxy
      editable: true
      secureJsonData:
        basicAuthPassword: >-
          mysupersecretpasswd
      name: prometheus
      url: 'https://prometheus-k8s.openshift-monitoring.svc.cluster.local:9091'
      jsonData:
        timeInterval: 5s
        tlsSkipVerify: true
      basicAuth: true
      isDefault: true
      version: 1
      type: prometheus
  name: default-datasources.yaml
