kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-replicas
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: px-db
  volumeMode: Filesystem
