apiVersion: batch/v1
kind: Job
metadata:
  name: test1-check
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      job-name: test1-check
  template:
    metadata:
      creationTimestamp: null
      labels:
        job-name: test1-check
    spec:
      containers:
      - command: ["/usr/bin/sh"]
        args:
        - -c
        - "cat /tmp/storage/test1.log | wc -l"
        image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
        imagePullPolicy: IfNotPresent
        name: test1-check
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/storage
          name: pwx-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - name: pwx-storage
          persistentVolumeClaim:
            claimName: pvc-replicas
