apiVersion: batch/v1
kind: Job
metadata:
  labels:
    type: perf
    test: randwrite-r2-j1
    product: pwx
  name: perf-randwrite-r2-j1
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      job-name: perf-randwrite-r2-j1
  template:
    metadata:
      creationTimestamp: null
      labels:
        job-name: perf-randwrite-r2-j1
    spec:
      containers:
      - command:
        - sh
        - -c
        - >-
          fio /randwrite.fio --minimal --output-format=json+
        image: quay.io/kamelott/fio
        imagePullPolicy: IfNotPresent
        name: perf-randwrite-r2-j1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /randwrite.fio
          name: fio
          subPath: randwrite.fio
        - mountPath: /tmp/storage
          name: pvc-perf-repl-2
      dnsPolicy: ClusterFirst
      restartPolicy: Never 
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 493
            name: fio
          name: fio
        - name: pvc-perf-repl-2
          persistentVolumeClaim:
            claimName: pvc-perf-repl-2
