kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-perf-repl-3
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ report_file_size|int + 1 }}Gi
  storageClassName: px-db
  volumeMode: Filesystem
