apiVersion: v1
data:
  fullwrite.fio: |
    #Full Sequential Write Test
    [global]
    size=10G
    filesize=10G
    filename=/tmp/storage/fiofile
    direct=1
    sync=0
    iodepth=32
    ioengine=libaio

    [full-write]
    bs=1M
    nrfiles=1
    randrepeat=0
    rw=write
    refill_buffers
    end_fsync=1
  randread.fio: |
    #Random Read Test
    [global]
    size=10G
    filesize=10G
    filename=/tmp/storage/fiofile
    direct=1
    sync=0
    iodepth=32
    ioengine=libaio

    [random-read]
    time_based
    runtime=60
    randrepeat=0
    invalidate=1
    verify=0
    verify_fatal=0
    numjobs=4
    rw=randread
    blocksize=4k
    group_reporting
  randwrite.fio: |
    #Random Write Test
    [global]
    size=10G
    filesize=10G
    filename=/tmp/storage/fiofile
    direct=1
    sync=0
    iodepth=32
    ioengine=libaio

    [random-write]
    time_based
    runtime=60
    randrepeat=0
    invalidate=1
    verify=0
    verify_fatal=0
    numjobs=4
    rw=randwrite
    blocksize=4k
    group_reporting
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: fio
