kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-perf-repl-2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 11Gi
  storageClassName: px-replicated
  volumeMode: Filesystem
