
[appendix]
= Engaging Digital IQ Global Support Services

[.normal]
Digital IQ(R) Support helps you get the most from your Digital IQ subscriptions. Below, please find information about the Digital IQ Customer Portal, Digital IQ phone support, your personal points of contact, and how to contact sales and customer service.

We’re always available to assist you. If at any time you are unable to reach your personal Digital IQ Support contacts, you can find contact information below for the global support leadership team, which is available to assist upon your request.

== Digital IQ portal:
The Digital IQ Customer Portal is an award-winning digital platform that delivers enterprise product knowledge, subscription resources, and technical expertise that can only come from Digital IQ.

== Digital IQ phone support:
Digital IQ technical support engineers are available through phone support to quickly troubleshoot and resolve problems. More information about your regional contact number and business hours can be found at: link:https://li9.com .

.Digital IQ SUPPORT CONTACTS
[cols=3,options=header,cols="1,2,2",width=90%]
|===
|TIER
|CONTACT NAME & INFORMATION +
Phone: direct (D) mobile (M)
|AVAILABILITY
|1
|World Wide Support +
+phone +
(+phone) +
link:https://li9.com/support/[]^1^
|24x7x365 +
Depending on severity as the first point of contact for Digital IQ support.
|===


<<<
== Customer service
In addition to Digital IQ Support, Digital IQ sales and customer service are available to assist you. If you have questions regarding sales, future product needs, or entitlements, please use the contact information provided below.

.Customer service
[cols=2,stripes="none",options=header,cols="1,<.<2"]
|===
|CONTACT NAME & INFORMATION |NOTES
|Customer Service, World Wide +
480.269.2344
|===

== Production support terms of service

[cols=4,options=header,cols="1,3,3,1,2"]
|===
|
|Self-support
|Standard
2+|Premium

|Hours of coverage
|N/A
|Standard business hours ^2^
2+|Standard business hours (24x7 for Severity 1 and 2) ^3^

|Support channel
|None
|Web and phone
2+|Web and phone

|Number of cases
|N/A
|Unlimited
2+|Unlimited

|Response times
|Initial and ongoing response
|Initial and ongoing response
|Initial response
|Ongoing response

|Severity 1
|N/A
|1 business hour
|1 hour
|1 hour or as agreed

|Severity 2
|N/A
|4 business hours
|2 hours
|4 hours or as agreed

|Severity 3
|N/A
|1 business day
|4 business hours
|8 business hours or as agreed

|Severity 4
|N/A
|2 business day
|8 business hours
|2 business days or as agreed

|===

== Digital IQ Support severity level definitions

Opening a support case online can make it easier to share technical data, error messages, and system information with your Digital IQ Support representative. Following the online submission with a phone call can reduce response time as well as potential errors in the capture of information.

Digital IQ recommends that you follow any Severity 1 and 2 online support case submissions with a phone call to your local support center.

Digital IQ Global Support Services uses the following definitions to classify issues:

=== Severity 1 (urgent)
A problem that severely impacts your use of the software in a production environment (such as loss of production data or in which your production systems are not functioning). The situation halts your business operations and no procedural workaround exists.

=== Severity 2 (high)
A problem where the software is functioning but your use in a production environment is severely reduced. The situation is causing a high impact to portions of your business operations and no procedural workaround exists.

=== Severity 3 (medium)
A problem that involves partial, non-critical loss of use of the software in a production environment or development environment. For production environments, there is a medium-to-low impact on your business, but your business continues to function, including by using a procedural workaround. For development environments, where the situation is causing your project to no longer continue or migrate into production.

=== Severity 4 (low)
A general usage question, reporting of a documentation error, or recommendation for a future product enhancement or modification. For production environments, there is low-to-no impact on your business or the performance or functionality of your system. For development environments, there is a medium-to-low impact on your business, but your business continues to function, including by using a procedural workaround.
